CREATE  TABLE IF NOT EXISTS `factory`.`generator` (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `modbus_address` TINYINT NOT NULL ,
  PRIMARY KEY (`id`) ,
  UNIQUE INDEX `modbus_address_UNIQUE` (`modbus_address` ASC) )
ENGINE = InnoDB;

CREATE  TABLE IF NOT EXISTS `factory`.`generator_data` (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `generator_id` INT NOT NULL ,
  `G_Ua` FLOAT NULL ,
  `G_Ub` FLOAT NULL ,
  `G_Uc` FLOAT NULL ,
  `G_Uab` FLOAT NULL ,
  `G_Ubc` FLOAT NULL ,
  `G_Uca` FLOAT NULL ,
  `L_Ua` FLOAT NULL ,
  `L_Ub` FLOAT NULL ,
  `L_Uc` FLOAT NULL ,
  `L_Uab` FLOAT NULL ,
  `L_Ubc` FLOAT NULL ,
  `L_Uca` FLOAT NULL ,
  `Ia` FLOAT NULL ,
  `Ib` FLOAT NULL ,
  `Ic` FLOAT NULL ,
  `Pa` FLOAT NULL ,
  `Pb` FLOAT NULL ,
  `Pc` FLOAT NULL ,
  `Qa` FLOAT NULL ,
  `Qb` FLOAT NULL ,
  `Qc` FLOAT NULL ,
  `Sa` FLOAT NULL ,
  `Sb` FLOAT NULL ,
  `Sc` FLOAT NULL ,
  `PFa` FLOAT NULL ,
  `PFb` FLOAT NULL ,
  `PFc` FLOAT NULL ,
  `P3Phases` FLOAT NULL ,
  `Q3Phases` FLOAT NULL ,
  `S3Phases` FLOAT NULL ,
  `PF3Phases` FLOAT NULL ,
  `G_RealFreq` FLOAT NULL ,
  `L_RealFreq` FLOAT NULL ,
  `I0` FLOAT NULL ,
  `PowerEnergy` FLOAT NULL ,
  `SpeedGuardStatus` FLOAT NULL ,
  `RPM` FLOAT NULL ,
  `Temperature1` FLOAT NULL ,
  `Temperature2` FLOAT NULL ,
  `Temperature3` FLOAT NULL ,
  `Temperature4` FLOAT NULL ,
  `Temperature5` FLOAT NULL ,
  `Temperature6` FLOAT NULL ,
  `Temperature7` FLOAT NULL ,
  `Temperature8` FLOAT NULL ,
  `Temperature9` FLOAT NULL ,
  `Temperature10` FLOAT NULL ,
  `Temperature11` FLOAT NULL ,
  `Temperature12` FLOAT NULL ,
  `Press1` FLOAT NULL ,
  `Press2` FLOAT NULL ,
  `Press3` FLOAT NULL ,
  `Press4` FLOAT NULL ,
  `ContactGroup1` FLOAT NULL ,
  `ContactGroup2` FLOAT NULL ,
  `ContactGroup3` FLOAT NULL ,
  `ContactGroup4` FLOAT NULL ,
  `WaterOpenAngle` FLOAT NULL ,
  `FuelLevel1` FLOAT NULL ,
  `FuelLevel2` FLOAT NULL ,
  `ValvePlace` FLOAT NULL ,
  `TimeStamp` TIMESTAMP NOT NULL ,
  PRIMARY KEY (`id`) ,
  INDEX `generator_fk_idx` (`generator_id` ASC) ,
  CONSTRAINT `generator_fk`
    FOREIGN KEY (`generator_id` )
    REFERENCES `factory`.`generator` (`id` )
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;