package com.factory.sure.data.pojos;
// Generated Jul 18, 2013 1:19:56 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * GeneratorData generated by hbm2java
 */
public class GeneratorData implements java.io.Serializable {
    private Integer id;
    private Date timeStamp;
    private Generator m_pGenerator;
    private Short mG_Ua;
    private Short mG_Ub;
    private Short mG_Uc;
    private Short mG_Uab;
    private Short mG_Ubc;
    private Short mG_Uca;
    private Short mL_Ua;
    private Short mL_Ub;
    private Short mL_Uc;
    private Short mL_Uab;
    private Short mL_Ubc;
    private Short mL_Uca;
    private Short mIa;
    private Short mIb;
    private Short mIc;
    private Short mPa;
    private Short mPb;
    private Short mPc;
    private Short mQa;
    private Short mQb;
    private Short mQc;
    private Short mSa;
    private Short mSb;
    private Short mSc;
    private Short mPFa;
    private Short mPFb;
    private Short mPFc;
    private Short mP3Phases;
    private Short mQ3Phases;
    private Short mS3Phases;
    private Short mPF3Phases;
    private Short mG_RealFreq;
    private Short mL_RealFreq;
    private Short mI0;
    private Short mPowerEnergy;
    private Short mSpeedGuardStatus;
    private Short mRPM;
    private Short mTemperature1;
    private Short mTemperature2;
    private Short mTemperature3;
    private Short mTemperature4;
    private Short mTemperature5;
    private Short mTemperature6;
    private Short mTemperature7;
    private Short mTemperature8;
    private Short mTemperature9;
    private Short mTemperature10;
    private Short mTemperature11;
    private Short mTemperature12;
    private Short mPress1;
    private Short mPress2;
    private Short mPress3;
    private Short mPress4;
    private Short mContactGroup1;
    private Short mContactGroup2;
    private Short mContactGroup3;
    private Short mContactGroup4;
    private Short mWaterOpenAngle;
    private Short mFuelLevel1;
    private Short mFuelLevel2;
    private Short mValvePlace;
    
    public GeneratorData() {        
    }

    public GeneratorData(Generator generator) {
        this.m_pGenerator = generator;
        resetAllValues();
    }

    public GeneratorData(Generator generator, Short GUa, Short GUb, Short GUc, Short GUab, Short GUbc, Short GUca, Short LUa, Short LUb, Short LUc, Short LUab, Short LUbc, Short LUca, Short ia, Short ib, Short ic, Short pa, Short pb, Short pc, Short qa, Short qb, Short qc, Short sa, Short sb, Short sc, Short pfa, Short pfb, Short pfc, Short p3phases, Short q3phases, Short s3phases, Short pf3phases, Short GRealFreq, Short LRealFreq, Short i0, Short powerEnergy, Short speedGuardStatus, Short rpm, Short temperature1, Short temperature2, Short temperature3, Short temperature4, Short temperature5, Short temperature6, Short temperature7, Short temperature8, Short temperature9, Short temperature10, Short temperature11, Short temperature12, Short press1, Short press2, Short press3, Short press4, Short contactGroup1, Short contactGroup2, Short contactGroup3, Short contactGroup4, Short waterOpenAngle, Short fuelLevel1, Short fuelLevel2, Short valvePlace) {
        this.m_pGenerator = generator;
        this.mG_Ua = GUa;
        this.mG_Ub = GUb;
        this.mG_Uc = GUc;
        this.mG_Uab = GUab;
        this.mG_Ubc = GUbc;
        this.mG_Uca = GUca;
        this.mL_Ua = LUa;
        this.mL_Ub = LUb;
        this.mL_Uc = LUc;
        this.mL_Uab = LUab;
        this.mL_Ubc = LUbc;
        this.mL_Uca = LUca;
        this.mIa = ia;
        this.mIb = ib;
        this.mIc = ic;
        this.mPa = pa;
        this.mPb = pb;
        this.mPc = pc;
        this.mQa = qa;
        this.mQb = qb;
        this.mQc = qc;
        this.mSa = sa;
        this.mSb = sb;
        this.mSc = sc;
        this.mPFa = pfa;
        this.mPFb = pfb;
        this.mPFc = pfc;
        this.mP3Phases = p3phases;
        this.mQ3Phases = q3phases;
        this.mS3Phases = s3phases;
        this.mPF3Phases = pf3phases;
        this.mG_RealFreq = GRealFreq;
        this.mL_RealFreq = LRealFreq;
        this.mI0 = i0;
        this.mPowerEnergy = powerEnergy;
        this.mSpeedGuardStatus = speedGuardStatus;
        this.mRPM = rpm;
        this.mTemperature1 = temperature1;
        this.mTemperature2 = temperature2;
        this.mTemperature3 = temperature3;
        this.mTemperature4 = temperature4;
        this.mTemperature5 = temperature5;
        this.mTemperature6 = temperature6;
        this.mTemperature7 = temperature7;
        this.mTemperature8 = temperature8;
        this.mTemperature9 = temperature9;
        this.mTemperature10 = temperature10;
        this.mTemperature11 = temperature11;
        this.mTemperature12 = temperature12;
        this.mPress1 = press1;
        this.mPress2 = press2;
        this.mPress3 = press3;
        this.mPress4 = press4;
        this.mContactGroup1 = contactGroup1;
        this.mContactGroup2 = contactGroup2;
        this.mContactGroup3 = contactGroup3;
        this.mContactGroup4 = contactGroup4;
        this.mWaterOpenAngle = waterOpenAngle;
        this.mFuelLevel1 = fuelLevel1;
        this.mFuelLevel2 = fuelLevel2;
        this.mValvePlace = valvePlace;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Date getTimeStamp() {
        return this.timeStamp;
    }

    public void setTimeStamp(Date timeStamp) {
        this.timeStamp = timeStamp;
    }

    public Generator getGenerator() {
        return this.m_pGenerator;
    }

    public void setGenerator(Generator generator) {
        this.m_pGenerator = generator;
    }

    public Short getG_Ua() {
        return this.mG_Ua;
    }

    public void setG_Ua(Short GUa) {
        this.mG_Ua = GUa;
    }

    public Short getG_Ub() {
        return this.mG_Ub;
    }

    public void setG_Ub(Short GUb) {
        this.mG_Ub = GUb;
    }

    public Short getG_Uc() {
        return this.mG_Uc;
    }

    public void setG_Uc(Short GUc) {
        this.mG_Uc = GUc;
    }

    public Short getG_Uab() {
        return this.mG_Uab;
    }

    public void setG_Uab(Short GUab) {
        this.mG_Uab = GUab;
    }

    public Short getG_Ubc() {
        return this.mG_Ubc;
    }

    public void setG_Ubc(Short GUbc) {
        this.mG_Ubc = GUbc;
    }

    public Short getG_Uca() {
        return this.mG_Uca;
    }

    public void setG_Uca(Short GUca) {
        this.mG_Uca = GUca;
    }

    public Short getL_Ua() {
        return this.mL_Ua;
    }

    public void setL_Ua(Short LUa) {
        this.mL_Ua = LUa;
    }

    public Short getL_Ub() {
        return this.mL_Ub;
    }

    public void setL_Ub(Short LUb) {
        this.mL_Ub = LUb;
    }

    public Short getL_Uc() {
        return this.mL_Uc;
    }

    public void setL_Uc(Short LUc) {
        this.mL_Uc = LUc;
    }

    public Short getL_Uab() {
        return this.mL_Uab;
    }

    public void setL_Uab(Short LUab) {
        this.mL_Uab = LUab;
    }

    public Short getL_Ubc() {
        return this.mL_Ubc;
    }

    public void setL_Ubc(Short LUbc) {
        this.mL_Ubc = LUbc;
    }

    public Short getL_Uca() {
        return this.mL_Uca;
    }

    public void setL_Uca(Short LUca) {
        this.mL_Uca = LUca;
    }

    public Short getIa() {
        return this.mIa;
    }

    public void setIa(Short ia) {
        this.mIa = ia;
    }

    public Short getIb() {
        return this.mIb;
    }

    public void setIb(Short ib) {
        this.mIb = ib;
    }

    public Short getIc() {
        return this.mIc;
    }

    public void setIc(Short ic) {
        this.mIc = ic;
    }

    public Short getPa() {
        return this.mPa;
    }

    public void setPa(Short pa) {
        this.mPa = pa;
    }

    public Short getPb() {
        return this.mPb;
    }

    public void setPb(Short pb) {
        this.mPb = pb;
    }

    public Short getPc() {
        return this.mPc;
    }

    public void setPc(Short pc) {
        this.mPc = pc;
    }

    public Short getQa() {
        return this.mQa;
    }

    public void setQa(Short qa) {
        this.mQa = qa;
    }

    public Short getQb() {
        return this.mQb;
    }

    public void setQb(Short qb) {
        this.mQb = qb;
    }

    public Short getQc() {
        return this.mQc;
    }

    public void setQc(Short qc) {
        this.mQc = qc;
    }

    public Short getSa() {
        return this.mSa;
    }

    public void setSa(Short sa) {
        this.mSa = sa;
    }

    public Short getSb() {
        return this.mSb;
    }

    public void setSb(Short sb) {
        this.mSb = sb;
    }

    public Short getSc() {
        return this.mSc;
    }

    public void setSc(Short sc) {
        this.mSc = sc;
    }

    public Short getPFa() {
        return this.mPFa;
    }

    public void setPFa(Short pfa) {
        this.mPFa = pfa;
    }

    public Short getPFb() {
        return this.mPFb;
    }

    public void setPFb(Short pfb) {
        this.mPFb = pfb;
    }

    public Short getPFc() {
        return this.mPFc;
    }

    public void setPFc(Short pfc) {
        this.mPFc = pfc;
    }

    public Short getP3Phases() {
        return this.mP3Phases;
    }

    public void setP3Phases(Short p3phases) {
        this.mP3Phases = p3phases;
    }

    public Short getQ3Phases() {
        return this.mQ3Phases;
    }

    public void setQ3Phases(Short q3phases) {
        this.mQ3Phases = q3phases;
    }

    public Short getS3Phases() {
        return this.mS3Phases;
    }

    public void setS3Phases(Short s3phases) {
        this.mS3Phases = s3phases;
    }

    public Short getPF3Phases() {
        return this.mPF3Phases;
    }

    public void setPF3Phases(Short pf3phases) {
        this.mPF3Phases = pf3phases;
    }

    public Short getG_RealFreq() {
        return this.mG_RealFreq;
    }

    public void setG_RealFreq(Short GRealFreq) {
        this.mG_RealFreq = GRealFreq;
    }

    public Short getL_RealFreq() {
        return this.mL_RealFreq;
    }

    public void setL_RealFreq(Short LRealFreq) {
        this.mL_RealFreq = LRealFreq;
    }

    public Short getI0() {
        return this.mI0;
    }

    public void setI0(Short i0) {
        this.mI0 = i0;
    }

    public Short getPowerEnergy() {
        return this.mPowerEnergy;
    }

    public void setPowerEnergy(Short powerEnergy) {
        this.mPowerEnergy = powerEnergy;
    }

    public Short getSpeedGuardStatus() {
        return this.mSpeedGuardStatus;
    }

    public void setSpeedGuardStatus(Short speedGuardStatus) {
        this.mSpeedGuardStatus = speedGuardStatus;
    }

    public Short getRPM() {
        return this.mRPM;
    }

    public void setRPM(Short rpm) {
        this.mRPM = rpm;
    }

    public Short getTemperature1() {
        return this.mTemperature1;
    }

    public void setTemperature1(Short temperature1) {
        this.mTemperature1 = temperature1;
    }

    public Short getTemperature2() {
        return this.mTemperature2;
    }

    public void setTemperature2(Short temperature2) {
        this.mTemperature2 = temperature2;
    }

    public Short getTemperature3() {
        return this.mTemperature3;
    }

    public void setTemperature3(Short temperature3) {
        this.mTemperature3 = temperature3;
    }

    public Short getTemperature4() {
        return this.mTemperature4;
    }

    public void setTemperature4(Short temperature4) {
        this.mTemperature4 = temperature4;
    }

    public Short getTemperature5() {
        return this.mTemperature5;
    }

    public void setTemperature5(Short temperature5) {
        this.mTemperature5 = temperature5;
    }

    public Short getTemperature6() {
        return this.mTemperature6;
    }

    public void setTemperature6(Short temperature6) {
        this.mTemperature6 = temperature6;
    }

    public Short getTemperature7() {
        return this.mTemperature7;
    }

    public void setTemperature7(Short temperature7) {
        this.mTemperature7 = temperature7;
    }

    public Short getTemperature8() {
        return this.mTemperature8;
    }

    public void setTemperature8(Short temperature8) {
        this.mTemperature8 = temperature8;
    }

    public Short getTemperature9() {
        return this.mTemperature9;
    }

    public void setTemperature9(Short temperature9) {
        this.mTemperature9 = temperature9;
    }

    public Short getTemperature10() {
        return this.mTemperature10;
    }

    public void setTemperature10(Short temperature10) {
        this.mTemperature10 = temperature10;
    }

    public Short getTemperature11() {
        return this.mTemperature11;
    }

    public void setTemperature11(Short temperature11) {
        this.mTemperature11 = temperature11;
    }

    public Short getTemperature12() {
        return this.mTemperature12;
    }

    public void setTemperature12(Short temperature12) {
        this.mTemperature12 = temperature12;
    }

    public Short getPress1() {
        return this.mPress1;
    }

    public void setPress1(Short press1) {
        this.mPress1 = press1;
    }

    public Short getPress2() {
        return this.mPress2;
    }

    public void setPress2(Short press2) {
        this.mPress2 = press2;
    }

    public Short getPress3() {
        return this.mPress3;
    }

    public void setPress3(Short press3) {
        this.mPress3 = press3;
    }

    public Short getPress4() {
        return this.mPress4;
    }

    public void setPress4(Short press4) {
        this.mPress4 = press4;
    }

    public Short getContactGroup1() {
        return this.mContactGroup1;
    }

    public void setContactGroup1(Short contactGroup1) {
        this.mContactGroup1 = contactGroup1;
    }

    public Short getContactGroup2() {
        return this.mContactGroup2;
    }

    public void setContactGroup2(Short contactGroup2) {
        this.mContactGroup2 = contactGroup2;
    }

    public Short getContactGroup3() {
        return this.mContactGroup3;
    }

    public void setContactGroup3(Short contactGroup3) {
        this.mContactGroup3 = contactGroup3;
    }

    public Short getContactGroup4() {
        return this.mContactGroup4;
    }

    public void setContactGroup4(Short contactGroup4) {
        this.mContactGroup4 = contactGroup4;
    }

    public Short getWaterOpenAngle() {
        return this.mWaterOpenAngle;
    }

    public void setWaterOpenAngle(Short waterOpenAngle) {
        this.mWaterOpenAngle = waterOpenAngle;
    }

    public Short getFuelLevel1() {
        return this.mFuelLevel1;
    }

    public void setFuelLevel1(Short fuelLevel1) {
        this.mFuelLevel1 = fuelLevel1;
    }

    public Short getFuelLevel2() {
        return this.mFuelLevel2;
    }

    public void setFuelLevel2(Short fuelLevel2) {
        this.mFuelLevel2 = fuelLevel2;
    }

    public Short getValvePlace() {
        return this.mValvePlace;
    }

    public void setValvePlace(Short valvePlace) {
        this.mValvePlace = valvePlace;
    }

    @Override
    public String toString() {
        return String.format("[Generator Data: GeneratorModbusAddress = %s, GUab = %s, GUbc = %s, GUca = %s]",
                this.m_pGenerator.getModbusAddress() + "",
                this.mG_Uab + "", 
                this.mG_Ubc + "",
                this.mG_Uca + "");
    }
    
    /**
     * Reset all of the data to null
     */
    public final void resetAllValues() {
        this.setContactGroup1(null);
        this.setContactGroup2(null);
        this.setContactGroup3(null);
        this.setContactGroup4(null);

        this.setFuelLevel1(null);
        this.setFuelLevel2(null);

        this.setG_RealFreq(null);
        this.setL_RealFreq(null);

        this.setG_Ua(null);
        this.setG_Uab(null);
        this.setG_Ub(null);
        this.setG_Ubc(null);
        this.setG_Uc(null);
        this.setG_Uca(null);

        this.setI0(null);
        this.setIa(null);
        this.setIb(null);
        this.setIc(null);

        this.setL_Ua(null);
        this.setL_Uab(null);
        this.setL_Ub(null);
        this.setL_Ubc(null);
        this.setL_Uc(null);
        this.setL_Uca(null);

        this.setP3Phases(null);
        this.setPF3Phases(null);

        this.setPFa(null);
        this.setPFb(null);
        this.setPFc(null);

        this.setPa(null);
        this.setPb(null);
        this.setPc(null);

        this.setPowerEnergy(null);

        this.setPress1(null);
        this.setPress2(null);
        this.setPress3(null);
        this.setPress4(null);

        this.setQ3Phases(null);

        this.setQa(null);
        this.setQb(null);
        this.setQc(null);

        this.setRPM(null);

        this.setS3Phases(null);
        this.setSa(null);
        this.setSb(null);
        this.setSc(null);

        this.setSpeedGuardStatus(null);

        this.setTemperature1(null);
        this.setTemperature2(null);
        this.setTemperature3(null);
        this.setTemperature4(null);
        this.setTemperature5(null);
        this.setTemperature6(null);
        this.setTemperature7(null);
        this.setTemperature8(null);
        this.setTemperature9(null);
        this.setTemperature10(null);
        this.setTemperature11(null);
        this.setTemperature12(null);

        this.setValvePlace(null);
        this.setWaterOpenAngle(null);
    }
    
    // TODO: delete this in the release version
    public void setRandomValues() {
        this.setContactGroup1((short)(Math.random() * 1000));
        this.setContactGroup2((short)(Math.random() * 1000));
        this.setContactGroup3((short)(Math.random() * 1000));
        this.setContactGroup4((short)(Math.random() * 1000));

        this.setFuelLevel1((short)(Math.random() * 1000));
        this.setFuelLevel2((short)(Math.random() * 1000));

        this.setG_RealFreq((short)(Math.random() * 1000));
        this.setL_RealFreq((short)(Math.random() * 1000));

        this.setG_Ua((short)(Math.random() * 1000));
        this.setG_Uab((short)(Math.random() * 1000));
        this.setG_Ub((short)(Math.random() * 1000));
        this.setG_Ubc((short)(Math.random() * 1000));
        this.setG_Uc((short)(Math.random() * 1000));
        this.setG_Uca((short)(Math.random() * 1000));

        this.setI0((short)(Math.random() * 1000));
        this.setIa((short)(Math.random() * 1000));
        this.setIb((short)(Math.random() * 1000));
        this.setIc((short)(Math.random() * 1000));

        this.setL_Ua((short)(Math.random() * 1000));
        this.setL_Uab((short)(Math.random() * 1000));
        this.setL_Ub((short)(Math.random() * 1000));
        this.setL_Ubc((short)(Math.random() * 1000));
        this.setL_Uc((short)(Math.random() * 1000));
        this.setL_Uca((short)(Math.random() * 1000));

        this.setP3Phases((short)(Math.random() * 1000));
        this.setPF3Phases((short)(Math.random() * 1000));

        this.setPFa((short)(Math.random() * 1000));
        this.setPFb((short)(Math.random() * 1000));
        this.setPFc((short)(Math.random() * 1000));

        this.setPa((short)(Math.random() * 1000));
        this.setPb((short)(Math.random() * 1000));
        this.setPc((short)(Math.random() * 1000));

        this.setPowerEnergy((short)(Math.random() * 1000));

        this.setPress1((short)(Math.random() * 1000));
        this.setPress2((short)(Math.random() * 1000));
        this.setPress3((short)(Math.random() * 1000));
        this.setPress4((short)(Math.random() * 1000));

        this.setQ3Phases((short)(Math.random() * 1000));

        this.setQa((short)(Math.random() * 1000));
        this.setQb((short)(Math.random() * 1000));
        this.setQc((short)(Math.random() * 1000));

        this.setRPM((short)(Math.random() * 1000));

        this.setS3Phases((short)(Math.random() * 1000));
        this.setSa((short)(Math.random() * 1000));
        this.setSb((short)(Math.random() * 1000));
        this.setSc((short)(Math.random() * 1000));

        this.setSpeedGuardStatus((short)(Math.random() * 1000));

        this.setTemperature1((short)(Math.random() * 1000));
        this.setTemperature2((short)(Math.random() * 1000));
        this.setTemperature3((short)(Math.random() * 1000));
        this.setTemperature4((short)(Math.random() * 1000));
        this.setTemperature5((short)(Math.random() * 1000));
        this.setTemperature6((short)(Math.random() * 1000));
        this.setTemperature7((short)(Math.random() * 1000));
        this.setTemperature8((short)(Math.random() * 1000));
        this.setTemperature9((short)(Math.random() * 1000));
        this.setTemperature10((short)(Math.random() * 1000));
        this.setTemperature11((short)(Math.random() * 1000));
        this.setTemperature12((short)(Math.random() * 1000));

        this.setValvePlace((short)(Math.random() * 1000));
        this.setWaterOpenAngle((short)(Math.random() * 1000));
    }
}
