package com.factory.sure.data.pojos;
// Generated Jul 18, 2013 1:19:56 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * GeneratorData generated by hbm2java
 */
public class GeneratorData implements java.io.Serializable {
    private Integer id;
    private Date timeStamp;
    private Generator m_pGenerator;
    private Float mG_Ua;
    private Float mG_Ub;
    private Float mG_Uc;
    private Float mG_Uab;
    private Float mG_Ubc;
    private Float mG_Uca;
    private Float mL_Ua;
    private Float mL_Ub;
    private Float mL_Uc;
    private Float mL_Uab;
    private Float mL_Ubc;
    private Float mL_Uca;
    private Float mIa;
    private Float mIb;
    private Float mIc;
    private Float mPa;
    private Float mPb;
    private Float mPc;
    private Float mQa;
    private Float mQb;
    private Float mQc;
    private Float mSa;
    private Float mSb;
    private Float mSc;
    private Float mPFa;
    private Float mPFb;
    private Float mPFc;
    private Float mP3Phases;
    private Float mQ3Phases;
    private Float mS3Phases;
    private Float mPF3Phases;
    private Float mG_RealFreq;
    private Float mL_RealFreq;
    private Float mI0;
    private Float mPowerEnergy;
    private Float mSpeedGuardStatus;
    private Float mRPM;
    private Float mTemperature1;
    private Float mTemperature2;
    private Float mTemperature3;
    private Float mTemperature4;
    private Float mTemperature5;
    private Float mTemperature6;
    private Float mTemperature7;
    private Float mTemperature8;
    private Float mTemperature9;
    private Float mTemperature10;
    private Float mTemperature11;
    private Float mTemperature12;
    private Float mPress1;
    private Float mPress2;
    private Float mPress3;
    private Float mPress4;
    private Float mContactGroup1;
    private Float mContactGroup2;
    private Float mContactGroup3;
    private Float mContactGroup4;
    private Float mWaterOpenAngle;
    private Float mFuelLevel1;
    private Float mFuelLevel2;
    private Float mValvePlace;
    
    public GeneratorData() {        
    }

    public GeneratorData(Generator generator) {
        this.m_pGenerator = generator;
        resetAllValues();
    }

    public GeneratorData(Generator generator, Float GUa, Float GUb, Float GUc, Float GUab, Float GUbc, Float GUca, Float LUa, Float LUb, Float LUc, Float LUab, Float LUbc, Float LUca, Float ia, Float ib, Float ic, Float pa, Float pb, Float pc, Float qa, Float qb, Float qc, Float sa, Float sb, Float sc, Float pfa, Float pfb, Float pfc, Float p3phases, Float q3phases, Float s3phases, Float pf3phases, Float GRealFreq, Float LRealFreq, Float i0, Float powerEnergy, Float speedGuardStatus, Float rpm, Float temperature1, Float temperature2, Float temperature3, Float temperature4, Float temperature5, Float temperature6, Float temperature7, Float temperature8, Float temperature9, Float temperature10, Float temperature11, Float temperature12, Float press1, Float press2, Float press3, Float press4, Float contactGroup1, Float contactGroup2, Float contactGroup3, Float contactGroup4, Float waterOpenAngle, Float fuelLevel1, Float fuelLevel2, Float valvePlace) {
        this.m_pGenerator = generator;
        this.mG_Ua = GUa;
        this.mG_Ub = GUb;
        this.mG_Uc = GUc;
        this.mG_Uab = GUab;
        this.mG_Ubc = GUbc;
        this.mG_Uca = GUca;
        this.mL_Ua = LUa;
        this.mL_Ub = LUb;
        this.mL_Uc = LUc;
        this.mL_Uab = LUab;
        this.mL_Ubc = LUbc;
        this.mL_Uca = LUca;
        this.mIa = ia;
        this.mIb = ib;
        this.mIc = ic;
        this.mPa = pa;
        this.mPb = pb;
        this.mPc = pc;
        this.mQa = qa;
        this.mQb = qb;
        this.mQc = qc;
        this.mSa = sa;
        this.mSb = sb;
        this.mSc = sc;
        this.mPFa = pfa;
        this.mPFb = pfb;
        this.mPFc = pfc;
        this.mP3Phases = p3phases;
        this.mQ3Phases = q3phases;
        this.mS3Phases = s3phases;
        this.mPF3Phases = pf3phases;
        this.mG_RealFreq = GRealFreq;
        this.mL_RealFreq = LRealFreq;
        this.mI0 = i0;
        this.mPowerEnergy = powerEnergy;
        this.mSpeedGuardStatus = speedGuardStatus;
        this.mRPM = rpm;
        this.mTemperature1 = temperature1;
        this.mTemperature2 = temperature2;
        this.mTemperature3 = temperature3;
        this.mTemperature4 = temperature4;
        this.mTemperature5 = temperature5;
        this.mTemperature6 = temperature6;
        this.mTemperature7 = temperature7;
        this.mTemperature8 = temperature8;
        this.mTemperature9 = temperature9;
        this.mTemperature10 = temperature10;
        this.mTemperature11 = temperature11;
        this.mTemperature12 = temperature12;
        this.mPress1 = press1;
        this.mPress2 = press2;
        this.mPress3 = press3;
        this.mPress4 = press4;
        this.mContactGroup1 = contactGroup1;
        this.mContactGroup2 = contactGroup2;
        this.mContactGroup3 = contactGroup3;
        this.mContactGroup4 = contactGroup4;
        this.mWaterOpenAngle = waterOpenAngle;
        this.mFuelLevel1 = fuelLevel1;
        this.mFuelLevel2 = fuelLevel2;
        this.mValvePlace = valvePlace;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Date getTimeStamp() {
        return this.timeStamp;
    }

    public void setTimeStamp(Date timeStamp) {
        this.timeStamp = timeStamp;
    }

    public Generator getGenerator() {
        return this.m_pGenerator;
    }

    public void setGenerator(Generator generator) {
        this.m_pGenerator = generator;
    }

    public Float getG_Ua() {
        return this.mG_Ua;
    }

    public void setG_Ua(Float GUa) {
        this.mG_Ua = GUa;
    }

    public Float getG_Ub() {
        return this.mG_Ub;
    }

    public void setG_Ub(Float GUb) {
        this.mG_Ub = GUb;
    }

    public Float getG_Uc() {
        return this.mG_Uc;
    }

    public void setG_Uc(Float GUc) {
        this.mG_Uc = GUc;
    }

    public Float getG_Uab() {
        return this.mG_Uab;
    }

    public void setG_Uab(Float GUab) {
        this.mG_Uab = GUab;
    }

    public Float getG_Ubc() {
        return this.mG_Ubc;
    }

    public void setG_Ubc(Float GUbc) {
        this.mG_Ubc = GUbc;
    }

    public Float getG_Uca() {
        return this.mG_Uca;
    }

    public void setG_Uca(Float GUca) {
        this.mG_Uca = GUca;
    }

    public Float getL_Ua() {
        return this.mL_Ua;
    }

    public void setL_Ua(Float LUa) {
        this.mL_Ua = LUa;
    }

    public Float getL_Ub() {
        return this.mL_Ub;
    }

    public void setL_Ub(Float LUb) {
        this.mL_Ub = LUb;
    }

    public Float getL_Uc() {
        return this.mL_Uc;
    }

    public void setL_Uc(Float LUc) {
        this.mL_Uc = LUc;
    }

    public Float getL_Uab() {
        return this.mL_Uab;
    }

    public void setL_Uab(Float LUab) {
        this.mL_Uab = LUab;
    }

    public Float getL_Ubc() {
        return this.mL_Ubc;
    }

    public void setL_Ubc(Float LUbc) {
        this.mL_Ubc = LUbc;
    }

    public Float getL_Uca() {
        return this.mL_Uca;
    }

    public void setL_Uca(Float LUca) {
        this.mL_Uca = LUca;
    }

    public Float getIa() {
        return this.mIa;
    }

    public void setIa(Float ia) {
        this.mIa = ia;
    }

    public Float getIb() {
        return this.mIb;
    }

    public void setIb(Float ib) {
        this.mIb = ib;
    }

    public Float getIc() {
        return this.mIc;
    }

    public void setIc(Float ic) {
        this.mIc = ic;
    }

    public Float getPa() {
        return this.mPa;
    }

    public void setPa(Float pa) {
        this.mPa = pa;
    }

    public Float getPb() {
        return this.mPb;
    }

    public void setPb(Float pb) {
        this.mPb = pb;
    }

    public Float getPc() {
        return this.mPc;
    }

    public void setPc(Float pc) {
        this.mPc = pc;
    }

    public Float getQa() {
        return this.mQa;
    }

    public void setQa(Float qa) {
        this.mQa = qa;
    }

    public Float getQb() {
        return this.mQb;
    }

    public void setQb(Float qb) {
        this.mQb = qb;
    }

    public Float getQc() {
        return this.mQc;
    }

    public void setQc(Float qc) {
        this.mQc = qc;
    }

    public Float getSa() {
        return this.mSa;
    }

    public void setSa(Float sa) {
        this.mSa = sa;
    }

    public Float getSb() {
        return this.mSb;
    }

    public void setSb(Float sb) {
        this.mSb = sb;
    }

    public Float getSc() {
        return this.mSc;
    }

    public void setSc(Float sc) {
        this.mSc = sc;
    }

    public Float getPFa() {
        return this.mPFa;
    }

    public void setPFa(Float pfa) {
        this.mPFa = pfa;
    }

    public Float getPFb() {
        return this.mPFb;
    }

    public void setPFb(Float pfb) {
        this.mPFb = pfb;
    }

    public Float getPFc() {
        return this.mPFc;
    }

    public void setPFc(Float pfc) {
        this.mPFc = pfc;
    }

    public Float getP3Phases() {
        return this.mP3Phases;
    }

    public void setP3Phases(Float p3phases) {
        this.mP3Phases = p3phases;
    }

    public Float getQ3Phases() {
        return this.mQ3Phases;
    }

    public void setQ3Phases(Float q3phases) {
        this.mQ3Phases = q3phases;
    }

    public Float getS3Phases() {
        return this.mS3Phases;
    }

    public void setS3Phases(Float s3phases) {
        this.mS3Phases = s3phases;
    }

    public Float getPF3Phases() {
        return this.mPF3Phases;
    }

    public void setPF3Phases(Float pf3phases) {
        this.mPF3Phases = pf3phases;
    }

    public Float getG_RealFreq() {
        return this.mG_RealFreq;
    }

    public void setG_RealFreq(Float GRealFreq) {
        this.mG_RealFreq = GRealFreq;
    }

    public Float getL_RealFreq() {
        return this.mL_RealFreq;
    }

    public void setL_RealFreq(Float LRealFreq) {
        this.mL_RealFreq = LRealFreq;
    }

    public Float getI0() {
        return this.mI0;
    }

    public void setI0(Float i0) {
        this.mI0 = i0;
    }

    public Float getPowerEnergy() {
        return this.mPowerEnergy;
    }

    public void setPowerEnergy(Float powerEnergy) {
        this.mPowerEnergy = powerEnergy;
    }

    public Float getSpeedGuardStatus() {
        return this.mSpeedGuardStatus;
    }

    public void setSpeedGuardStatus(Float speedGuardStatus) {
        this.mSpeedGuardStatus = speedGuardStatus;
    }

    public Float getRPM() {
        return this.mRPM;
    }

    public void setRPM(Float rpm) {
        this.mRPM = rpm;
    }

    public Float getTemperature1() {
        return this.mTemperature1;
    }

    public void setTemperature1(Float temperature1) {
        this.mTemperature1 = temperature1;
    }

    public Float getTemperature2() {
        return this.mTemperature2;
    }

    public void setTemperature2(Float temperature2) {
        this.mTemperature2 = temperature2;
    }

    public Float getTemperature3() {
        return this.mTemperature3;
    }

    public void setTemperature3(Float temperature3) {
        this.mTemperature3 = temperature3;
    }

    public Float getTemperature4() {
        return this.mTemperature4;
    }

    public void setTemperature4(Float temperature4) {
        this.mTemperature4 = temperature4;
    }

    public Float getTemperature5() {
        return this.mTemperature5;
    }

    public void setTemperature5(Float temperature5) {
        this.mTemperature5 = temperature5;
    }

    public Float getTemperature6() {
        return this.mTemperature6;
    }

    public void setTemperature6(Float temperature6) {
        this.mTemperature6 = temperature6;
    }

    public Float getTemperature7() {
        return this.mTemperature7;
    }

    public void setTemperature7(Float temperature7) {
        this.mTemperature7 = temperature7;
    }

    public Float getTemperature8() {
        return this.mTemperature8;
    }

    public void setTemperature8(Float temperature8) {
        this.mTemperature8 = temperature8;
    }

    public Float getTemperature9() {
        return this.mTemperature9;
    }

    public void setTemperature9(Float temperature9) {
        this.mTemperature9 = temperature9;
    }

    public Float getTemperature10() {
        return this.mTemperature10;
    }

    public void setTemperature10(Float temperature10) {
        this.mTemperature10 = temperature10;
    }

    public Float getTemperature11() {
        return this.mTemperature11;
    }

    public void setTemperature11(Float temperature11) {
        this.mTemperature11 = temperature11;
    }

    public Float getTemperature12() {
        return this.mTemperature12;
    }

    public void setTemperature12(Float temperature12) {
        this.mTemperature12 = temperature12;
    }

    public Float getPress1() {
        return this.mPress1;
    }

    public void setPress1(Float press1) {
        this.mPress1 = press1;
    }

    public Float getPress2() {
        return this.mPress2;
    }

    public void setPress2(Float press2) {
        this.mPress2 = press2;
    }

    public Float getPress3() {
        return this.mPress3;
    }

    public void setPress3(Float press3) {
        this.mPress3 = press3;
    }

    public Float getPress4() {
        return this.mPress4;
    }

    public void setPress4(Float press4) {
        this.mPress4 = press4;
    }

    public Float getContactGroup1() {
        return this.mContactGroup1;
    }

    public void setContactGroup1(Float contactGroup1) {
        this.mContactGroup1 = contactGroup1;
    }

    public Float getContactGroup2() {
        return this.mContactGroup2;
    }

    public void setContactGroup2(Float contactGroup2) {
        this.mContactGroup2 = contactGroup2;
    }

    public Float getContactGroup3() {
        return this.mContactGroup3;
    }

    public void setContactGroup3(Float contactGroup3) {
        this.mContactGroup3 = contactGroup3;
    }

    public Float getContactGroup4() {
        return this.mContactGroup4;
    }

    public void setContactGroup4(Float contactGroup4) {
        this.mContactGroup4 = contactGroup4;
    }

    public Float getWaterOpenAngle() {
        return this.mWaterOpenAngle;
    }

    public void setWaterOpenAngle(Float waterOpenAngle) {
        this.mWaterOpenAngle = waterOpenAngle;
    }

    public Float getFuelLevel1() {
        return this.mFuelLevel1;
    }

    public void setFuelLevel1(Float fuelLevel1) {
        this.mFuelLevel1 = fuelLevel1;
    }

    public Float getFuelLevel2() {
        return this.mFuelLevel2;
    }

    public void setFuelLevel2(Float fuelLevel2) {
        this.mFuelLevel2 = fuelLevel2;
    }

    public Float getValvePlace() {
        return this.mValvePlace;
    }

    public void setValvePlace(Float valvePlace) {
        this.mValvePlace = valvePlace;
    }

    @Override
    public String toString() {
        return String.format("[Generator Data: GeneratorModbusAddress = %s, GUab = %s, GUbc = %s, GUca = %s]",
                this.m_pGenerator.getModbusAddress() + "",
                this.mG_Uab + "", 
                this.mG_Ubc + "",
                this.mG_Uca + "");
    }
    
    /**
     * Reset all of the data to null
     */
    public final void resetAllValues() {
        this.setContactGroup1(null);
        this.setContactGroup2(null);
        this.setContactGroup3(null);
        this.setContactGroup4(null);

        this.setFuelLevel1(null);
        this.setFuelLevel2(null);

        this.setG_RealFreq(null);
        this.setL_RealFreq(null);

        this.setG_Ua(null);
        this.setG_Uab(null);
        this.setG_Ub(null);
        this.setG_Ubc(null);
        this.setG_Uc(null);
        this.setG_Uca(null);

        this.setI0(null);
        this.setIa(null);
        this.setIb(null);
        this.setIc(null);

        this.setL_Ua(null);
        this.setL_Uab(null);
        this.setL_Ub(null);
        this.setL_Ubc(null);
        this.setL_Uc(null);
        this.setL_Uca(null);

        this.setP3Phases(null);
        this.setPF3Phases(null);

        this.setPFa(null);
        this.setPFb(null);
        this.setPFc(null);

        this.setPa(null);
        this.setPb(null);
        this.setPc(null);

        this.setPowerEnergy(null);

        this.setPress1(null);
        this.setPress2(null);
        this.setPress3(null);
        this.setPress4(null);

        this.setQ3Phases(null);

        this.setQa(null);
        this.setQb(null);
        this.setQc(null);

        this.setRPM(null);

        this.setS3Phases(null);
        this.setSa(null);
        this.setSb(null);
        this.setSc(null);

        this.setSpeedGuardStatus(null);

        this.setTemperature1(null);
        this.setTemperature2(null);
        this.setTemperature3(null);
        this.setTemperature4(null);
        this.setTemperature5(null);
        this.setTemperature6(null);
        this.setTemperature7(null);
        this.setTemperature8(null);
        this.setTemperature9(null);
        this.setTemperature10(null);
        this.setTemperature11(null);
        this.setTemperature12(null);

        this.setValvePlace(null);
        this.setWaterOpenAngle(null);
    }
    
    // TODO: delete this in the release version
    public void setRandomValues() {
        this.setContactGroup1((float)(Math.random() * 1000));
        this.setContactGroup2((float)(Math.random() * 1000));
        this.setContactGroup3((float)(Math.random() * 1000));
        this.setContactGroup4((float)(Math.random() * 1000));

        this.setFuelLevel1((float)(Math.random() * 1000));
        this.setFuelLevel2((float)(Math.random() * 1000));

        this.setG_RealFreq((float)(Math.random() * 1000));
        this.setL_RealFreq((float)(Math.random() * 1000));

        this.setG_Ua((float)(Math.random() * 1000));
        this.setG_Uab((float)(Math.random() * 1000));
        this.setG_Ub((float)(Math.random() * 1000));
        this.setG_Ubc((float)(Math.random() * 1000));
        this.setG_Uc((float)(Math.random() * 1000));
        this.setG_Uca((float)(Math.random() * 1000));

        this.setI0((float)(Math.random() * 1000));
        this.setIa((float)(Math.random() * 1000));
        this.setIb((float)(Math.random() * 1000));
        this.setIc((float)(Math.random() * 1000));

        this.setL_Ua((float)(Math.random() * 1000));
        this.setL_Uab((float)(Math.random() * 1000));
        this.setL_Ub((float)(Math.random() * 1000));
        this.setL_Ubc((float)(Math.random() * 1000));
        this.setL_Uc((float)(Math.random() * 1000));
        this.setL_Uca((float)(Math.random() * 1000));

        this.setP3Phases((float)(Math.random() * 1000));
        this.setPF3Phases((float)(Math.random() * 1000));

        this.setPFa((float)(Math.random() * 1000));
        this.setPFb((float)(Math.random() * 1000));
        this.setPFc((float)(Math.random() * 1000));

        this.setPa((float)(Math.random() * 1000));
        this.setPb((float)(Math.random() * 1000));
        this.setPc((float)(Math.random() * 1000));

        this.setPowerEnergy((float)(Math.random() * 1000));

        this.setPress1((float)(Math.random() * 1000));
        this.setPress2((float)(Math.random() * 1000));
        this.setPress3((float)(Math.random() * 1000));
        this.setPress4((float)(Math.random() * 1000));

        this.setQ3Phases((float)(Math.random() * 1000));

        this.setQa((float)(Math.random() * 1000));
        this.setQb((float)(Math.random() * 1000));
        this.setQc((float)(Math.random() * 1000));

        this.setRPM((float)(Math.random() * 1000));

        this.setS3Phases((float)(Math.random() * 1000));
        this.setSa((float)(Math.random() * 1000));
        this.setSb((float)(Math.random() * 1000));
        this.setSc((float)(Math.random() * 1000));

        this.setSpeedGuardStatus((float)(Math.random() * 1000));

        this.setTemperature1((float)(Math.random() * 1000));
        this.setTemperature2((float)(Math.random() * 1000));
        this.setTemperature3((float)(Math.random() * 1000));
        this.setTemperature4((float)(Math.random() * 1000));
        this.setTemperature5((float)(Math.random() * 1000));
        this.setTemperature6((float)(Math.random() * 1000));
        this.setTemperature7((float)(Math.random() * 1000));
        this.setTemperature8((float)(Math.random() * 1000));
        this.setTemperature9((float)(Math.random() * 1000));
        this.setTemperature10((float)(Math.random() * 1000));
        this.setTemperature11((float)(Math.random() * 1000));
        this.setTemperature12((float)(Math.random() * 1000));

        this.setValvePlace((float)(Math.random() * 1000));
        this.setWaterOpenAngle((float)(Math.random() * 1000));
    }
}
